### ISSUE TITLE
Refactoring transmitere date intre doua taburi

### ISSUE THREAD

**Issue by VFX10** [viorelfilip/internship-2020#23]
### Descriere:

Va exista un Service care va contine o lista cu toate cererile existente. 
Trimiterea unei cereri de la un tab la altul se va realiza prin transmiterea indexului din lista a cererii prin parametru URL in loc de tot obiectul.

**Comment by patriciamic** [comment]
Transmiterea de date se face trimitand index-ul elementului din lista ca parametru. 
Este implementat intre toate tab-urile
